version: "3.8"

services:
  workspace:
    container_name: openeo-argoworkflows-executor-devcontainer
    network_mode: "host"
    build:
      context: ../
      dockerfile: ".devcontainer/Dockerfile"
      target: devcontainer
    volumes:
      - ../:/openeo-argoworkflows-executor
    tty: true