name: Tests

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - '**'
  workflow_dispatch:

env:
  POETRY_VERSION: 1.8.3

jobs:
  tests_api:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          subFolder: openeo_argoworkflows/executor
          # Change this to be your CI task/script
          runCmd: |
            cwd
            ls
            poetry config virtualenvs.in-project true
            poetry install --with dev --all-extras
            poetry run pytest 
